{{- if and .Values.psp.create .Values.psp.spec -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "dellhw_exporter.fullname" . }}
spec:
  {{- with .Values.psp.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dellhw_exporter.fullname" . }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ include "dellhw_exporter.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dellhw_exporter.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "dellhw_exporter.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "dellhw_exporter.serviceAccountName" . }}
  namespace: {{ .Release.Name }}
{{- end }}
